home-status:
    path: /
    controller: App\Vending\Infrastructure\UI\Controller\StatusController
    methods: GET

machine-service:
    path: /service
    controller: App\Vending\Infrastructure\UI\Controller\ServiceController
    methods: POST

user-insert-coin:
    path: /credit/{value}
    controller: App\Vending\Infrastructure\UI\Controller\CreditController
    methods: GET
