#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

status:
    path: /
    controller: App\VendingMachine\Infrastructure\UI\Controller\StatusController
    methods: GET
